name: Playwright Tests

#  REQUIRED for GitHub Pages deployment
permissions:
  contents: write

on:
  push:
    branches: [main, master]
  # pull_request:
  #  branches: [main, master]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
      # Checkout repo
      - name: Checkout code
        uses: actions/checkout@v4

      # Setup Node
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # Install dependencies
      - name: Install dependencies
        run: npm ci

      # Install Java (needed for Allure)
      - name: Install Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "8"

      # Install Playwright browsers
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      # Run tests (don't fail pipeline)
      - name: Run Playwright tests
        run: npx playwright test || true
      # Install Allure CLI (official)
      - name: Install Allure CLI
        run: npm install -g allure-commandline --save-dev
      # Generate Allure report
      - name: Generate Allure Report
        if: always()
        run: |
          allure generate allure-results -o allure-report --clean ||true

      # Debug step (VERY IMPORTANT for troubleshooting)
      - name: Debug Allure Files
        if: always()
        run: |
          echo "===== ROOT ====="
          ls -la
          echo "===== ALLURE RESULTS ====="
          ls -la allure-results || echo "No allure-results found"
          echo "===== ALLURE REPORT ====="
          ls -la allure-report || echo "No allure-report found"

      # Upload report as artifact
      - name: Upload Allure Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report/
          retention-days: 30

      # Deploy to GitHub Pages
      - name: Deploy Allure Report to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-report